version: 2.1

orbs:
  go: circleci/go@1.7.3

jobs:
  test:
    executor:
      name: go/default #
      tag: "1.23.2"
    steps:
      - checkout # checkout source code
      - go/load-cache # Load cached Go modules.
      - go/mod-download # Run 'go mod download'.
      - go/save-cache # Save Go modules to cache.
      - go/test: # Runs 'go test ./...' but includes extensive parameterization for finer tuning.
          covermode: atomic
          failfast: true
          race: true
      - persist_to_workspace:
          root: ~/project
          paths: .

  build_image:
    executor:
      name: go/default #
      tag: "1.23.2"
    steps:
      - run: echo "Building the image"

workflows:
  test_and_build:
    jobs:
      - test
      - build_image:
          requires:
            - test
